server:
  port: 8080


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicio-foto
          uri: http://localhost:8092
          predicates:
            - Path=/foto/**
        - id: servicio-usuario
          uri: http://localhost:8091
          predicates:
            - Path=/usuario/**